import{byId,downloadJson,escapeHtml,extendBounds}from"./core/utils.js";
import{fetchJson,firstAvailable,shortId,agencyName,agencyPaths,metadataFor}from"./core/data.js";
import{prepareRoutes}from"./core/routes.js";
import{addNetwork,removeNetwork,setVisibility,routeLayerIds}from"./map/layers.js";
import{renderAgency}from"./ui/render.js";
import{showAnalytics}from"./ui/analytics.js";
import{showRouteDetails,showStopDetails}from"./ui/details.js";
const CFG=window.TRANSIT_APP_CONFIG;
const state={map:null,centroids:null,metadata:{},selected:null,routes:null,stops:null,bounds:null,hoveredRoute:null,selectedRoute:null};
function status(message,error=false){const box=byId("status");box.textContent=message;box.style.borderLeftColor=error?"#c63b36":"#6795c8"}
async function loadAgency(feature){state.selected=feature;const properties=feature.properties||{},paths=agencyPaths(properties),metadata=metadataFor(properties,state.metadata);byId("loadingOverlay").hidden=false;try{state.routes=prepareRoutes(await fetchJson(paths.routes,"Routes GeoJSON"));try{state.stops=await fetchJson(paths.stops,"Stops GeoJSON")}catch{state.stops={type:"FeatureCollection",features:[]}}addNetwork(state.map,state.routes,state.stops);state.bounds=new mapboxgl.LngLatBounds();state.routes.features.forEach(f=>extendBounds(state.bounds,f.geometry));fitAgency();renderAgency(properties,metadata,state.routes,state.stops);bindNetworkInteractions(metadata);status(`Loaded ${agencyName(properties)}. Select a route or stop for details.`)}catch(error){console.error(error);status(error.message,true)}finally{byId("loadingOverlay").hidden=true}}
function fitAgency(){if(state.bounds&&!state.bounds.isEmpty())state.map.fitBounds(state.bounds,{padding:{top:55,bottom:55,left:430,right:55},maxZoom:13,duration:850})}
function bindNetworkInteractions(metadata){routeLayerIds().forEach(layer=>{state.map.on("mousemove",layer,event=>{const feature=event.features?.[0];if(!feature)return;if(state.hoveredRoute!==null)state.map.setFeatureState({source:"agency-routes",id:state.hoveredRoute},{hover:false});state.hoveredRoute=feature.id;state.map.setFeatureState({source:"agency-routes",id:feature.id},{hover:true});state.map.getCanvas().style.cursor="pointer"});state.map.on("mouseleave",layer,()=>{if(state.hoveredRoute!==null)state.map.setFeatureState({source:"agency-routes",id:state.hoveredRoute},{hover:false});state.hoveredRoute=null;state.map.getCanvas().style.cursor=""});state.map.on("click",layer,event=>{const feature=event.features[0];if(state.selectedRoute!==null)state.map.setFeatureState({source:"agency-routes",id:state.selectedRoute},{selected:false});state.selectedRoute=feature.id;state.map.setFeatureState({source:"agency-routes",id:feature.id},{selected:true});showRouteDetails(feature.properties,metadata)})});["stops","stations"].forEach(layer=>state.map.getLayer(layer)&&state.map.on("click",layer,event=>showStopDetails(event.features[0].properties,metadata)));document.querySelectorAll("[data-route-key]").forEach(button=>button.onclick=()=>{const found=state.routes.features.find(f=>f.properties._routeKey===button.dataset.routeKey);if(found)showRouteDetails(found.properties,metadata)})}
function clearAgency(){state.selected=null;removeNetwork(state.map);byId("agencyPanel").hidden=true;byId("featureDrawer").hidden=true;status("National agency view. Select a centroid or search for an agency.")}
async function initialize(){const token=byId("tokenInput").value.trim();if(!token)return status("Enter a Mapbox public token.",true);localStorage.setItem("transit_mapbox_token",token);mapboxgl.accessToken=token;if(state.map)return;state.map=new mapboxgl.Map({container:"map",style:"mapbox://styles/mapbox/light-v11",center:CFG.initialCenter,zoom:CFG.initialZoom});state.map.addControl(new mapboxgl.NavigationControl(),"top-right");state.map.addControl(new mapboxgl.FullscreenControl(),"top-right");state.map.on("load",async()=>{try{[state.centroids,state.metadata]=await Promise.all([firstAvailable(CFG.fallbackCentroidPaths,"Agency centroids"),firstAvailable(CFG.metadataPaths,"Agency metadata").catch(()=>({}))]);if(Array.isArray(state.metadata))state.metadata=Object.fromEntries(state.metadata.map(x=>[x.feed_id||x.short_id,x]));addCentroidLayers();byId("agencySearch").disabled=false;status(`Loaded ${state.centroids.features.length.toLocaleString()} agency networks.`)}catch(error){console.error(error);status(error.message,true)}})}
function addCentroidLayers(){state.map.addSource("agency-centroids",{type:"geojson",data:state.centroids,cluster:true,clusterMaxZoom:9,clusterRadius:42});state.map.addLayer({id:"clusters",type:"circle",source:"agency-centroids",filter:["has","point_count"],paint:{"circle-color":["step",["get","point_count"],"#43a8c6",20,"#2479bb",75,"#334e88"],"circle-radius":["step",["get","point_count"],16,20,21,75,27],"circle-stroke-color":"#fff","circle-stroke-width":2}});state.map.addLayer({id:"cluster-count",type:"symbol",source:"agency-centroids",filter:["has","point_count"],layout:{"text-field":["get","point_count_abbreviated"],"text-size":11},paint:{"text-color":"#fff"}});state.map.addLayer({id:"agency-centroids",type:"circle",source:"agency-centroids",filter:["!",["has","point_count"]],paint:{"circle-radius":["interpolate",["linear"],["zoom"],3,4,10,7],"circle-color":"#1769e0","circle-stroke-color":"#fff","circle-stroke-width":1.5}});state.map.addLayer({id:"agency-labels",type:"symbol",source:"agency-centroids",filter:["!",["has","point_count"]],minzoom:5,layout:{"text-field":["coalesce",["get","agency_name"],["get","agency"],"Transit agency"],"text-size":10,"text-offset":[0,1.1],"text-anchor":"top","text-max-width":15,"text-optional":true},paint:{"text-color":"#26374b","text-halo-color":"#fff","text-halo-width":1.5}});state.map.on("click","clusters",event=>{const feature=state.map.queryRenderedFeatures(event.point,{layers:["clusters"]})[0];state.map.getSource("agency-centroids").getClusterExpansionZoom(feature.properties.cluster_id,(error,zoom)=>!error&&state.map.easeTo({center:feature.geometry.coordinates,zoom}))});["agency-centroids","agency-labels"].forEach(layer=>state.map.on("click",layer,event=>loadAgency(event.features[0])))}
function bindUi(){const saved=localStorage.getItem("transit_mapbox_token");if(saved)byId("tokenInput").value=saved;byId("toggleToken").onclick=()=>{const input=byId("tokenInput"),show=input.type==="password";input.type=show?"text":"password";byId("toggleToken").textContent=show?"Hide":"Show"};byId("loadMapBtn").onclick=initialize;byId("clearAgencyBtn").onclick=clearAgency;byId("fitAgencyBtn").onclick=fitAgency;byId("closeDrawerBtn").onclick=()=>byId("featureDrawer").hidden=true;byId("closeAnalyticsBtn").onclick=()=>byId("analyticsModal").hidden=true;byId("analyticsModal").onclick=e=>{if(e.target===byId("analyticsModal"))byId("analyticsModal").hidden=true};byId("analyticsBtn").onclick=()=>showAnalytics(state.selected.properties,metadataFor(state.selected.properties,state.metadata),state.routes,state.stops);document.querySelectorAll(".tab").forEach(tab=>tab.onclick=()=>{document.querySelectorAll(".tab,.tab-panel").forEach(x=>x.classList.remove("active"));tab.classList.add("active");byId(`${tab.dataset.tab}Tab`).classList.add("active")});byId("routesToggle").onchange=e=>setVisibility(state.map,["route-glow",...routeLayerIds(),"route-hover"],e.target.checked);byId("stopsToggle").onchange=e=>setVisibility(state.map,["stops","stations"],e.target.checked);byId("labelsToggle").onchange=e=>setVisibility(state.map,["route-labels"],e.target.checked);bindSearch();bindExports()}
function bindSearch(){byId("agencySearch").oninput=event=>{const q=event.target.value.trim().toLowerCase(),box=byId("searchResults");if(q.length<2||!state.centroids){box.hidden=true;return}const hits=state.centroids.features.filter(f=>{const p=f.properties||{};return[agencyName(p),p.state,p.state_hint,p.ntd_id,p.metadata_ntd_id,shortId(p)].some(v=>String(v||"").toLowerCase().includes(q))}).slice(0,20);box.innerHTML=hits.map((f,i)=>`<button class="search-result" data-index="${i}"><strong>${escapeHtml(agencyName(f.properties))}</strong><small>${escapeHtml(f.properties.state||f.properties.state_hint||"")} · ${escapeHtml(shortId(f.properties))}</small></button>`).join("");box.hidden=!hits.length;box.querySelectorAll("button").forEach(button=>button.onclick=()=>{box.hidden=true;loadAgency(hits[Number(button.dataset.index)])})}}
function bindExports(){byId("exportRoutesBtn").onclick=()=>state.routes&&downloadJson(state.routes,`${shortId(state.selected.properties)}_routes.geojson`);byId("exportStopsBtn").onclick=()=>state.stops&&downloadJson(state.stops,`${shortId(state.selected.properties)}_stops.geojson`);byId("exportMetadataBtn").onclick=()=>state.selected&&downloadJson(metadataFor(state.selected.properties,state.metadata),`${shortId(state.selected.properties)}_metadata.json`);byId("exportPackageBtn").onclick=()=>state.selected&&downloadJson({agency:state.selected.properties,metadata:metadataFor(state.selected.properties,state.metadata),routes:state.routes,stops:state.stops},`${shortId(state.selected.properties)}_transit_package.json`)}
bindUi();
